### ISSUE TITLE
Option to filter IPv6 link-local addresses from being imported.

### ISSUE THREAD

**Issue by ggiesen** [h4ndzdatm0ld/nautobot-ssot-vsphere#17]
### Environment
* Nautobot version:  1.3.10
* nautobot-ssot-vsphere version:  0.2.5

### Proposed Functionality
Add an option to filter IPv6 link-local addresses. Nautobot-ssot-vsphere currently imports IPv6 link-local addresses (FE80::/10). These are local to the link, and don't really have much in terms of meaning in an IPAM/DCIM. Also, they can be duplicated across links (even on the same device), which Nautobot's model doesn't support.

**Comment by h4ndzdatm0ld** [comment]
Hey there! This is a great suggestion. I'll see about adding it in the next couple days.

**Comment by h4ndzdatm0ld** [comment]
Ticket auto closed, but the fix was tested and pushed new release. 

Thanks for checking it out and raising an issue. Let me know if you have any other feedback :)
