### ISSUE TITLE
After each sync, manually added Clusters are deleted 

### ISSUE THREAD

**Issue by TravelTrexIT** [h4ndzdatm0ld/nautobot-ssot-vsphere#22]
### Environment
* Python version:  3.10
* Nautobot version:  1.4.0
* nautobot-ssot-vsphere version:  0.1.3

### Expected Behavior
We have multiple clusters from different vendors, but only the data from one vSphere Cluster is synced with nautobot. We expect that data which is not on the vSphere Cluster site is still available after the sync. 

### Observed Behavior
When the sync is done, every other Cluster is deleted. 

### Steps to Reproduce
1. Create additional Cluster "new Cluster"
2. Sync
3. "new Cluster" is gone

**Comment by h4ndzdatm0ld** [comment]
Hey there, @TravelTrexIT  This seems like a reasonable request. I'll put some thought into how to approach this.

**Comment by h4ndzdatm0ld** [comment]
Hi, I am taking a look at this finally. Have you tried running the job with "Sync Tagged Only"? I think this would satisfy this use-case without any modification. Please let me know if I am misunderstanding.

**Comment by TravelTrexIT** [comment]
@h4ndzdatm0ld Thank you. I tried the suggestion option and it worked. Thank you. I will close this issue then.
