### ISSUE TITLE
After installing nautobot-ssot-vsphere, nautobot is unable to start.

### ISSUE THREAD

**Issue by apast0r** [h4ndzdatm0ld/nautobot-ssot-vsphere#32]
### Environment
* Python version:  3.8
* Nautobot version:  1.4.7
* nautobot-ssot-vsphere version:  0.1.3

I have a running installation of nautobot. Then I added the plugin nautobot-ssot-vsphere, after restarted nautbot, it is unable to start and throws the next error:  `Model class nautobot_ssot.models.Sync doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS`.

The full error trace is attached with the name `trace.txt`

### Steps to Reproduce
1. Fresh nautobot installation.
2. Install nautobot-ssot-vsphere python package
3. Configure nautobot_config.py with the required parameters.
4. Start nautubot.

My nautobot_config.py:

```
PLUGINS = ["nautobot_device_onboarding","nautobot_plugin_nornir","nautobot_golden_config","nautobot_ssot_vsphere"]

PLUGINS_CONFIG = {
    "nautobot_plugin_nornir": {
        "nornir_settings": {
            "credentials": "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars",
            "runner": {
                "plugin": "threaded",
                "options": {
                    "num_workers": 20,
                },
            },
        },
    },
    "nautobot_golden_config": {
        "per_feature_bar_width": 0.15,
        "per_feature_width": 13,
        "per_feature_height": 4,
        "enable_backup": True,
        "enable_compliance": True,
        "enable_intended": True,
        "enable_sotagg": True,
        "sot_agg_transposer": None,
        "enable_postprocessing": False,
        "postprocessing_callables": [],
        "postprocessing_subscribed": [],
        "platform_slug_map": None,
        # "get_custom_compliance": "my.custom_compliance.func"
    },
    "nautobot_ssot_vsphere": {
        "VSPHERE_URI": os.getenv("VSPHERE_URI"),
        "VSPHERE_USERNAME": os.getenv("VSPHERE_USERNAME"),
        "VSPHERE_PASSWORD": os.getenv("VSPHERE_PASSWORD"),
        "VSPHERE_VERIFY_SSL": is_truthy(os.getenv("VSPHERE_VERIFY_SSL", False)),
    },
}
```
[trace.txt](https://github.com/h4ndzdatm0ld/nautobot-ssot-vsphere/files/9919620/trace.txt)

**Comment by h4ndzdatm0ld** [comment]
Hey there! Looks like you are missing the ssot-plugin.

'''
PLUGINS = ["nautobot_ssot_vsphere", "nautobot_ssot"]
'''

**Comment by apast0r** [comment]
Hi @h4ndzdatm0ld ,
That was the issue.

I thought that nautobot_ssot was a plugin skeleton and not a dependency.

Thanks for the quick response.
